version: "3.9"  # optional since v1.27.0
services:

  backend:
    image: 075730933478.dkr.ecr.ap-northeast-2.amazonaws.com/backend-spring:49b3444
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hidiscuss?autoReconnect=true
      - SPRING_DATASOURCE_HIKARI_USERNAME=root
      - SPRING_DATASOURCE_HIKARI_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
      - SPRING_CONFIG_LOCATION=classpath:config/*/application.yml
      - HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect      
      - GITHUB_REDIRECT_URI=http://localhost/api/login/oauth2/code/github
      - JWT_SECRET_KEY=token-secret-key-for-hyun-backend-spring-boot-login-aabbccddeeefffffeeffeffef
      - HOME_URL=http://localhost
    depends_on:
      - db
  #websocket:
  #  image: nestjs-test:latest ## TBD - pull from registry
  #  environment:
  #    - WEBSOCKET_PORT=8080
  frontend:
    image: 075730933478.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:7a5d697
  web:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hidiscuss
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  api-generator:
    build:
      context: ./api-generator
    environment:
     - SWAGGER_API_URL=http://backend:8080/v2/api-docs
     - BUILD_DIR=/app/dist
    volumes:
      - ./dist:/app/dist
    depends_on:
      - backend