version: "3.9"  # optional since v1.27.0
services:
  websocket:
    image: nestjs-test:latest ## TBD - pull from registry
    environment:
      - WEBSOCKET_PORT=8080
  frontend:
    image: nextjs-test:latest ## TBD - pull from registry
  web:
    image: nginx:1.20
    ports:
      - "80:80"
    depends_on:
      - websocket
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    restart: always
